autoupdate: true
mrdkOH: 95
mrdkFQ: 5
updatetime: 0 20 1 * * ?
Jplp: 1
Rplp: 1
dbcomment: true
plpapi: false
fishcd: 120
fish_sale:
  - type: ğŸŸ
    price: 3
  - type: ğŸ¡
    price: 5
  - type: ğŸ¦
    price: 5
  - type: ğŸ¦€
    price: 5
  - type: ğŸ 
    price: 10
  - type: ğŸ™
    price: 8
  - type: ğŸ¦‘
    price: 8
  - type: ğŸ¦ˆ
    price: 15
  - type: ğŸ‹
    price: 20
  - type: ğŸ¬
    price: 12
  - type: ğŸ¦­
    price: 18
  - type: ğŸ¦
    price: 25
  - type: ğŸ¦ª
    price: 7
  - type: ğŸš
    price: 4
  - type: ğŸª¼
    price: 9
  - type: ğŸ‰
    price: 50
  - type: ğŸ§œâ™€ï¸
    price: 35
  - type: ğŸ§œâ™‚ï¸
    price: 32
  - type: ğŸ”´ğŸ 
    price: 16
  - type: ğŸ”µğŸ¦
    price: 14
  - type: ğŸŸ¡ğŸ¡
    price: 19
  - type: ğŸŒ¿
    price: 2
  - type: ğŸª¸
    price: 11
  - type: ğŸ‘Ÿ
    price: 0
  - type: ğŸ§¦
    price: 0
  - type: ğŸ—‘ï¸
    price: 0
  - type: ğŸŒ
    price: 6
  - type: ğŸ¦‚
    price: 13
  - type: ğŸ¦«
    price: 17
  - type: ğŸ¦”
    price: 21
  - type: ğŸ¦©
    price: 22
  - type: ğŸ¦¤
    price: 23
  - type: ğŸ¦œ
    price: 24
  - type: ğŸ¦¢
    price: 26
  - type: ğŸ¦š
    price: 27
  - type: ğŸ¦ƒ
    price: 28
  - type: ğŸ§
    price: 29
  - type: ğŸ¦
    price: 30
  - type: ğŸ¸
    price: 31
  - type: ğŸŠ
    price: 33
  - type: ğŸ¦–
    price: 34
  - type: ğŸ¦•
    price: 36
  - type: ğŸŒŠ
    price: 37
  - type: ğŸŒŒ
    price: 38
  - type: ğŸŒ€
    price: 39
  - type: ğŸ’§
    price: 40
  - type: ğŸŒˆ
    price: 41
  - type: ğŸ”±
    price: 42
  - type: ğŸ£
    price: 43
  - type: âš“
    price: 44
  - type: ğŸš¤
    price: 45
  - type: ğŸ›¶
    price: 46
  - type: ğŸ§¨
    price: 0
  - type: ğŸ’
    price: 0
  - type: ğŸ•¶ï¸
    price: 0
